"use client"

import { ColumnDef } from "@tanstack/react-table"

export type ReportAndInsight = {
  id: string
  department: string
  focus_area: string
  time_period: string
  total_feedbacks: number
  average_rating: number
  pending_issues: number
  top_rated_department: string
  lowest_rated_department: string
  generated_by: string
  created_on: string
}

// Column definition
export const report_columns: ColumnDef<ReportAndInsight>[] = [
  {
    accessorKey: "id",
    header: "Report ID",
  },
  {
    accessorKey: "department",
    header: "Department",
  },
  {
    accessorKey: "focus_area",
    header: "Focus Area",
  },
  {
    accessorKey: "time_period",
    header: "Time Period",
  },
  {
    accessorKey: "total_feedbacks",
    header: "Total Feedbacks",
  },
  {
    accessorKey: "average_rating",
    header: "Average Rating",
  },
  {
    accessorKey: "pending_issues",
    header: "Pending Issues",
  },
  {
    accessorKey: "top_rated_department",
    header: "Top Rated Department",
  },
  {
    accessorKey: "lowest_rated_department",
    header: "Lowest Rated Department",
  },
  {
    accessorKey: "generated_by",
    header: "Generated By",
  },
  {
    accessorKey: "created_on",
    header: "Created On",
  },
]

// Async function to return mock report data
export async function getReports(): Promise<ReportAndInsight[]> {
  return [
    {
      id: "r001",
      department: "Support",
      focus_area: "Customer Satisfaction",
      time_period: "Q1 2025",
      total_feedbacks: 450,
      average_rating: 4.3,
      pending_issues: 12,
      top_rated_department: "Sales",
      lowest_rated_department: "IT",
      generated_by: "Alice Johnson",
      created_on: "2025-04-10",
    },
    {
      id: "r002",
      department: "Sales",
      focus_area: "Product Feedback",
      time_period: "Q2 2025",
      total_feedbacks: 520,
      average_rating: 4.6,
      pending_issues: 8,
      top_rated_department: "Marketing",
      lowest_rated_department: "Support",
      generated_by: "Brian Smith",
      created_on: "2025-07-15",
    },
    {
      id: "r003",
      department: "HR",
      focus_area: "Employee Engagement",
      time_period: "Q3 2025",
      total_feedbacks: 310,
      average_rating: 4.1,
      pending_issues: 5,
      top_rated_department: "HR",
      lowest_rated_department: "Finance",
      generated_by: "Carla Reyes",
      created_on: "2025-09-05",
    },
    {
      id: "r004",
      department: "IT",
      focus_area: "System Performance",
      time_period: "Q3 2025",
      total_feedbacks: 275,
      average_rating: 3.9,
      pending_issues: 15,
      top_rated_department: "Development",
      lowest_rated_department: "Support",
      generated_by: "Daniel Kim",
      created_on: "2025-09-25",
    },
    {
      id: "r005",
      department: "Marketing",
      focus_area: "Campaign Efficiency",
      time_period: "Q4 2025",
      total_feedbacks: 610,
      average_rating: 4.7,
      pending_issues: 3,
      top_rated_department: "Marketing",
      lowest_rated_department: "Operations",
      generated_by: "Emma Thompson",
      created_on: "2025-10-30",
    },
  ]
}
